version: "3.7"
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3030:3030"

    environment:
      APP_LISTEN_PORT: 3030
      APP_JWT_SECRET: secret

    depends_on:
      - postgres

  postgres:
    image: postgres:latest

    ports:
      - "5432:5432"

    volumes:
      - pg-data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"

    depends_on:
      - postgres

volumes:
  pg-data:
